SELECT *
FROM partidos;

SELECT * FROM user

SELECT 'El '||NOMBRECOMPLETO||' es el partido de '||PRESIDENTE|| ' y resultado ha sido de 0'||RESULTADO||' en las elecciones '|| NOMBRE ||' de tipo '||TIPO
FROM partidos, EVENTOS_RESULTADOS, EVENTOS;


SELECT p.NOMBRE||', provincia de '||l.NOMBRE
FROM provincias p, localidades l
ORDER BY l.NOMBRE;

DESCRIBE CONSULTAS;
DESCRIBE CONSULTAS_DATOS;
DESCRIBE EVENTOS;
DESCRIBE EVENTOS_RESULTADOS;
DESCRIBE LOCALIDADES;
DESCRIBE PARTIDOS;
DESCRIBE PROVINCIAS;
DESCRIBE VOTANTES;

SELECT *
from VOTANTES;

SELECT NOMBRE ||' de tipo '|| TIPO "Convocatorias"
FROM Eventos;

